// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type DeleteByID struct {
	ID string `json:"id"`
}

type GetByID struct {
	ID string `json:"id"`
}

type Gets struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type Mutation struct {
}

type NewTodo struct {
	Task string `json:"task"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Query struct {
}

type Todo struct {
	ID          string     `json:"id"`
	Task        string     `json:"task"`
	IsCompleted bool       `json:"is_completed"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
	UpdatedAt   time.Time  `json:"updated_at"`
	User        *User      `json:"user"`
}

type UpdateTodo struct {
	Task        string     `json:"task"`
	ID          string     `json:"id"`
	IsCompleted bool       `json:"is_completed"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type UpdateUser struct {
	UserID    string    `json:"user_id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	UserID    string    `json:"user_id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Todo      []*Todo   `json:"todo"`
}
